linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godox
    - godot
    - gomnd
    - lll
    - nestif
    - testpackage
    - wsl
