language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.x

env:
  - GO111MODULE=on

install:
  - make install-tools

script:
  - make coverage.out
  - make lint
  - make format
  - git diff --exit-code
  - if [ -n "$COVERALLS_TOKEN" ]; then goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; fi

services:
  - docker

sudo: false
